### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by wreck3d** [kylecoburn/PokeBot#54]
Could you make it so the Bot resets within Mt. Moon if it's behind instead of waiting until it exits the cave? Would make it faster to get more runs in instead of completing the full cave, then resetting.

**Comment by RenaKunisaki** [comment]
I guess technically it doesn't know how long Mt Moon takes until it's done, but in general more opportunistic resets would be nice. If it's had too many encounters in Mt Moon or is taking a long time to even reach the next floor, or if Nidoran is taking way too much damage and/or doing way too little to Caterpie, it's probably safe to reset right away.

There are cases where it won't reset until it's done a task, even though it's clear well in advance. For example, encountering a Pidgey on route 2, running away, and then immediately resetting because it's taking too long to find a Nidoran.

I also saw a more interesting case, where it fought through the trainers on Route 3, stepped into the grass, got an encounter and immediately reset because it was out of balls. Obviously quite a waste of time, since it would have last used a ball to catch Nidoran (or possibly Pidgey right afterward), so it could have noticed right then and there instead of spending another 10 minutes.

(Of course, an even better strategy would be to just skip looking for encounters there when out of balls, or buy them on the way out of Pewter if possible, but that's beyond the scope of this issue...)

**Comment by kylecoburn** [comment]
No plans for this, no, although beast mode already effectively supports this. After the intro, the bot only resets following major points of rng.
